---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: wtgos
description: wtgOS - Bluefin-DX + Google dev tools for Framework 13.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 40

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
      - source: usr
        destination: /usr

  - from-file: core-rpms.yml
  - from-file: terminal-tools.yml

  - type: systemd
    system:
      enable:
        - podman.socket

  - type: kargs
    kargs:
      - amd_pstate=active
      - amdgpu.sg_display=0

  - type: justfiles
    include:
      - wtgOS.just

  - from-file: flatpaks.yml

  - type: signing
