---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluefin-framework-antigravity
description: Highly specialized, cryptographically signed, immutable OS for Framework 13 with Quarantined AI.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
      - source: usr
        destination: /usr

  - type: rpm-ostree
    install:
      - bats  # Kept so BATS is available on the live host for post-install validation

  - type: kargs
    kargs:
      - amd_pstate=active
      - amdgpu.sg_display=0

  - type: justfiles
    include:
      - antigravity.just

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe

  - type: signing
